// Auto-generated by deploy script — 2026-04-03T12:48:30.857Z
export const GRIEVANCE_REGISTRY_ABI = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "complaintId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "escalationLevel",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "ComplaintEscalated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "complaintId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "citizen",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "department",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "ComplaintFiled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "complaintId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "ComplaintRejected",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "complaintId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "ComplaintResolved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "complaintId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "department",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "ComplaintResponded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "string",
        "name": "name",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "official",
        "type": "address"
      }
    ],
    "name": "DepartmentRegistered",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "SLA_DURATION",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_complaintId",
        "type": "uint256"
      }
    ],
    "name": "approveResolution",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "complaintCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "complaints",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "citizen",
        "type": "address"
      },
      {
        "internalType": "string",
        "name": "department",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "title",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "description",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "ipfsHash",
        "type": "string"
      },
      {
        "internalType": "enum GrievanceRegistry.ComplaintStatus",
        "name": "status",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "createdAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "responseDeadline",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "escalated",
        "type": "bool"
      },
      {
        "internalType": "bool",
        "name": "citizenApproved",
        "type": "bool"
      },
      {
        "internalType": "string",
        "name": "responseText",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "respondedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint8",
        "name": "escalationLevel",
        "type": "uint8"
      },
      {
        "internalType": "bool",
        "name": "isAnonymous",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_department",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "_title",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "_description",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "_ipfsHash",
        "type": "string"
      },
      {
        "internalType": "bool",
        "name": "_isAnonymous",
        "type": "bool"
      }
    ],
    "name": "createComplaint",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "departmentNames",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "name": "departmentStats",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "totalComplaints",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "resolvedComplaints",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "slaBreaches",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "falseResolutions",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "escalations",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "lastUpdated",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "name": "departments",
    "outputs": [
      {
        "internalType": "string",
        "name": "name",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "official",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "exists",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_complaintId",
        "type": "uint256"
      }
    ],
    "name": "escalateComplaint",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getAllComplaints",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "id",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "citizen",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "department",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "title",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "description",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "ipfsHash",
            "type": "string"
          },
          {
            "internalType": "enum GrievanceRegistry.ComplaintStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "createdAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "responseDeadline",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "escalated",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "citizenApproved",
            "type": "bool"
          },
          {
            "internalType": "string",
            "name": "responseText",
            "type": "string"
          },
          {
            "internalType": "uint256",
            "name": "respondedAt",
            "type": "uint256"
          },
          {
            "internalType": "uint8",
            "name": "escalationLevel",
            "type": "uint8"
          },
          {
            "internalType": "bool",
            "name": "isAnonymous",
            "type": "bool"
          }
        ],
        "internalType": "struct GrievanceRegistry.Complaint[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getAllDepartmentNames",
    "outputs": [
      {
        "internalType": "string[]",
        "name": "",
        "type": "string[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_id",
        "type": "uint256"
      }
    ],
    "name": "getComplaint",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "id",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "citizen",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "department",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "title",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "description",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "ipfsHash",
            "type": "string"
          },
          {
            "internalType": "enum GrievanceRegistry.ComplaintStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "createdAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "responseDeadline",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "escalated",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "citizenApproved",
            "type": "bool"
          },
          {
            "internalType": "string",
            "name": "responseText",
            "type": "string"
          },
          {
            "internalType": "uint256",
            "name": "respondedAt",
            "type": "uint256"
          },
          {
            "internalType": "uint8",
            "name": "escalationLevel",
            "type": "uint8"
          },
          {
            "internalType": "bool",
            "name": "isAnonymous",
            "type": "bool"
          }
        ],
        "internalType": "struct GrievanceRegistry.Complaint",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_citizen",
        "type": "address"
      }
    ],
    "name": "getComplaintsByCitizen",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "id",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "citizen",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "department",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "title",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "description",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "ipfsHash",
            "type": "string"
          },
          {
            "internalType": "enum GrievanceRegistry.ComplaintStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "createdAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "responseDeadline",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "escalated",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "citizenApproved",
            "type": "bool"
          },
          {
            "internalType": "string",
            "name": "responseText",
            "type": "string"
          },
          {
            "internalType": "uint256",
            "name": "respondedAt",
            "type": "uint256"
          },
          {
            "internalType": "uint8",
            "name": "escalationLevel",
            "type": "uint8"
          },
          {
            "internalType": "bool",
            "name": "isAnonymous",
            "type": "bool"
          }
        ],
        "internalType": "struct GrievanceRegistry.Complaint[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_dept",
        "type": "string"
      }
    ],
    "name": "getComplaintsByDepartment",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "id",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "citizen",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "department",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "title",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "description",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "ipfsHash",
            "type": "string"
          },
          {
            "internalType": "enum GrievanceRegistry.ComplaintStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "createdAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "responseDeadline",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "escalated",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "citizenApproved",
            "type": "bool"
          },
          {
            "internalType": "string",
            "name": "responseText",
            "type": "string"
          },
          {
            "internalType": "uint256",
            "name": "respondedAt",
            "type": "uint256"
          },
          {
            "internalType": "uint8",
            "name": "escalationLevel",
            "type": "uint8"
          },
          {
            "internalType": "bool",
            "name": "isAnonymous",
            "type": "bool"
          }
        ],
        "internalType": "struct GrievanceRegistry.Complaint[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getDepartmentCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_index",
        "type": "uint256"
      }
    ],
    "name": "getDepartmentNameByIndex",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_dept",
        "type": "string"
      }
    ],
    "name": "getDepartmentScore",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_dept",
        "type": "string"
      }
    ],
    "name": "getDepartmentStats",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "totalComplaints",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "resolvedComplaints",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "slaBreaches",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "falseResolutions",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "escalations",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "score",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_name",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "_official",
        "type": "address"
      }
    ],
    "name": "registerDepartment",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_complaintId",
        "type": "uint256"
      }
    ],
    "name": "rejectResolution",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_complaintId",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "_responseText",
        "type": "string"
      }
    ],
    "name": "respondToComplaint",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_name",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "_official",
        "type": "address"
      }
    ],
    "name": "updateDepartmentOfficial",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
];
