// Auto-generated by deploy script — 2026-04-03T12:48:30.855Z
export const CONTRACT_ADDRESSES = {
  "GrievanceRegistry": "0x0409Dc247747FdBB1419d3Efdd406BBf84635F36",
  "network": "baseSepolia",
  "chainId": 84532,
  "deployedAt": "2026-04-03T12:48:30.855Z"
};
