const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("🚀 Deploying GrievanceChain contracts to", hre.network.name, "...\n");

  const [deployer] = await hre.ethers.getSigners();
  
  if (!deployer) {
    console.error("❌ No deployer account found!");
    console.error("Please make sure you have added your PRIVATE_KEY to the .env file in the root directory.");
    process.exit(1);
  }

  console.log("Deployer address:", deployer.address);
  console.log("Balance:", hre.ethers.formatEther(await hre.ethers.provider.getBalance(deployer.address)), "ETH\n");

  // Deploy GrievanceRegistry (CorruptionScore library is linked automatically)
  const GrievanceRegistry = await hre.ethers.getContractFactory("GrievanceRegistry");
  const registry = await GrievanceRegistry.deploy();
  await registry.waitForDeployment();

  const registryAddress = await registry.getAddress();
  console.log("✅ GrievanceRegistry deployed to:", registryAddress);

  // Export addresses for frontend
  const addresses = {
    GrievanceRegistry: registryAddress,
    network: hre.network.name,
    chainId: hre.network.config.chainId || 1337,
    deployedAt: new Date().toISOString()
  };

  const outputDir = path.join(__dirname, "../../frontend/src/constants");
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write addresses
  fs.writeFileSync(
    path.join(outputDir, "addresses.js"),
    `// Auto-generated by deploy script — ${new Date().toISOString()}\nexport const CONTRACT_ADDRESSES = ${JSON.stringify(addresses, null, 2)};\n`
  );

  // Write ABI
  const artifact = await hre.artifacts.readArtifact("GrievanceRegistry");
  fs.writeFileSync(
    path.join(outputDir, "abi.js"),
    `// Auto-generated by deploy script — ${new Date().toISOString()}\nexport const GRIEVANCE_REGISTRY_ABI = ${JSON.stringify(artifact.abi, null, 2)};\n`
  );

  console.log("\n📦 Contract addresses and ABI exported to frontend/src/constants/");
  console.log("\nDeployment complete! 🎉");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("❌ Deployment failed:", error);
    process.exit(1);
  });
